# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.define vm_name = "cdh1"  do |config|
  		config.vm.provider "virtualbox" do |v|
  			v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "1024",'--cpus', 1]
  		end
  		config.vm.box = "centos6.5"
  		config.vm.hostname =vm_name
  		config.ssh.username ="vagrant"
  		config.ssh.password="vagrant"
  		config.vm.network :private_network, ip: "192.168.56.121"
    	config.vm.provision :shell, :path => "bootstrap.sh",keep_color: true
    end

end
